### ISSUE TITLE
iframe che rimanda a mappa su cartodb

### ISSUE THREAD

**Issue by giuragu** [giuragu/fire#1]
In index.html l'iframe con link alla mappa interattiva (superficie percorsa dal fuoco in Italia) predisposta su carto db non viene visualizzata. @nelsonmau credo il motivo sia che nonostante il link sia funzionante la relativa mappa in cartodb non sia ancora stata "pubblicata".
@nelsonmau che mi dici?

**Comment by nelsonmau** [comment]
sì, sembrerebbe questo il problema... clicca su 'publish' in alto a destra...
